---
development:
  cloud_name: <%= ENV['CLOUD_NAME'] %> dub3gpx9t
  api_key: <%= ENV['CLOUD_KEY'] %> '245546139894559'
  api_secret: <%= ENV['CLOUD_SECRET'] %> QbLBJ_KvlEvJPKkyF6xW5B7nB1Q
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: <%= ENV['CLOUD_NAME'] %>
  api_key: <%= ENV['CLOUD_KEY'] %>
  api_secret: <%= ENV['CLOUD_SECRET'] %>
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: <%= ENV['CLOUD_NAME'] %>
  api_key: <%= ENV['CLOUD_KEY'] %>
  api_secret: <%= ENV['CLOUD_SECRET'] %>
  enhance_image_tag: true
  static_image_support: false
